FROM golang:1.6.3
MAINTAINER jaehue@jang.io

# install go package
RUN go get github.com/codegangsta/negroni && \
    go get github.com/gorilla/mux && \
   	go get github.com/dgrijalva/jwt-go && \
   	go get github.com/gorilla/websocket && \
   	go get github.com/satori/go.uuid && \
   	go get github.com/spf13/viper && \
   	go get github.com/unrolled/render && \
   	go get github.com/smartystreets/goconvey && \
	go get github.com/jinzhu/configor && \
    go get github.com/streadway/amqp && \
    go get github.com/mattn/go-sqlite3 && \
    go get github.com/go-sql-driver/mysql && \
    go get github.com/go-xorm/xorm && \
    go get github.com/moul/http2curl && \
    go get github.com/smallnest/goreq && \
    go get golang.org/x/oauth2 && \
    go get gopkg.in/yaml.v2 && \
    go get github.com/fatih/structs && \
    go get github.com/jaehue/anyq && \
    go get gopkg.in/mgo.v2 && \
    go get github.com/Sirupsen/logrus